services:
    wesnoth.registrationage.listener:
        class: wesnoth\registrationage\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
